# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproperty',
            name='property_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='name',
            field=models.TextField(),
        ),
    ]
