# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0003_auto_20161119_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3)),
                ('mean', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=2)),
                ('is_value', models.CharField(max_length=2)),
                ('cf', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.CharField(max_length=50)),
                ('right', models.CharField(max_length=10)),
                ('cf', models.FloatField()),
            ],
        ),
    ]
