# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0004_fact_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftFactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RightFactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.CreateModel(
            name='RuleModel',
            fields=[
                ('left', models.CharField(max_length=50)),
                ('right', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='expert_system.RightFactModel')),
                ('cf', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='leftfactmodel',
            name='rule_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.RuleModel'),
        ),
    ]
