# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0005_auto_20161207_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.CharField(max_length=50)),
                ('right', models.CharField(max_length=10)),
                ('cf', models.FloatField()),
            ],
        ),
    ]
