# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0007_remove_rulemodel_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulemodel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rulemodel',
            name='right',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expert_system.RightFactModel'),
        ),
    ]
